# Jekyll configuration for GitHub Pages
title: Bitrix CDN Server
description: Высокопроизводительный CDN сервер для автоматической оптимизации изображений Битрикс сайтов
author: Alexandr Chibilyaev
email: info@aachibilyaev.com
url: https://aachibilyaev.github.io
baseurl: /bitrix-cdn

# GitHub repository
github_username: AAChibilyaev
repository: AAChibilyaev/bitrix-cdn

# Theme settings
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links
  - jemoji

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
      sidebar: true

# Navigation
navigation:
  - title: Главная
    url: /
  - title: Документация
    url: /docs/
  - title: Quick Start
    url: /#quick-start
  - title: GitHub
    url: https://github.com/AAChibilyaev/bitrix-cdn

# Features for SEO
google_analytics: 
twitter:
  username: 
  card: summary
social:
  name: Alexandr Chibilyaev
  links:
    - https://github.com/AAChibilyaev
    - https://aachibilyaev.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Exclude files from build
exclude:
  - docker/
  - scripts/
  - monitoring/
  - nginx/
  - systemd/
  - logs/
  - "*.sh"
  - "*.example"
  - docker-compose*.yml
  - Makefile
  - LICENSE
  - .github/
  - .git/
  - .gitignore
  - .env*

# Include specific files
include:
  - index.md
  - README.md
  - docs/
  - _config.yml

# Mermaid support for diagrams
mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

# Performance optimizations
sass:
  style: compressed

# Timezone
timezone: Europe/Moscow