global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'default'
      continue: true

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:8088/health'
        send_resolved: true
    # Telegram настройки - раскомментируйте и настройте .env файл
    # telegram_configs:
    #   - bot_token: '${TELEGRAM_BOT_TOKEN}'
    #     chat_id: '${TELEGRAM_CHAT_ID}'
    #     parse_mode: 'HTML'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
