global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bitrix-cdn'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # NGINX monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          cdn: 'termokit'

  # Redis monitoring через Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          cdn: 'termokit'

  # Docker containers monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['172.25.0.1:9323']  # Требует docker metrics exporter
        labels:
          service: 'docker'

  # ИСПРАВЛЕНО: WebP Converter HTTP API metrics
  - job_name: 'webp-converter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webp-converter:8080']
        labels:
          service: 'webp-converter'
          cdn: 'termokit'
  
  # Node Exporter для системных метрик
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          cdn: 'termokit'